# Setup directories
genericdirectories_directories:
  - path: "/home/webmaster/domains"
    owner: "webmaster"
    group: "www-data"
    mode: "6755"
    recurse: "yes"
  - path: "/home/webmaster/domains/tmp"
    owner: "webmaster"
    group: "www-data"
    mode: "6775"
    recurse: "yes"
  - path: "/home/webmaster/domains/www"
    owner: "webmaster"
    group: "www-data"
    mode: "6755"
    recurse: "yes"
  - path: "/home/webmaster/domains/www/html"
    owner: "webmaster"
    group: "www-data"
    mode: "6755"
    recurse: "yes"
  - path: "/home/webmaster/domains/www/logs"
    owner: "www-data"
    group: "webmaster"
    mode: "6755"
    recurse: "yes"
  - path: "/home/webmaster/domains/www/html/sites/default/files"
    owner: "www-data"
    group: "webmaster"
    mode: "6777"
    recurse: "yes"
  - path: "/home/webmaster/domains/www/html/sites/default/private"
    owner: "www-data"
    group: "webmaster"
    mode: "6777"
    recurse: "yes"
  - path: "/home/webmaster/domains/www/html/tmp"
    owner: "www-data"
    group: "webmaster"
    mode: "6777"
    recurse: "yes"
