nginx_sites:
  "{{ site_name }}":
    - listen 80
    - server_name {{ site_name }} www.{{ site_name }}
    - access_log /var/log/nginx/{{ site_name }}-access.log main
    - error_log /var/log/nginx/{{ site_name }}-error.log
    - root {{ site_path }}/html
    - charset {{ charset_nginx }}
    - if ($bad_bot) {return 444;}
    - if ($bad_referer) { return 444;  }
    - if ($not_allowed_method) {return 405;}
    - fastcgi_keep_conn on
    - location ~* /sites/default/files/styles/ {
      access_log off;
      expires max;
      error_page 404 = @rewrite;}
    - location ~* ^.+\.(css|ico|cur|js|jpe?g|gif|htc|ico|png|html|xml|otf|ttf|eot|woff2?|svg|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf|woff|ogg|mp4|wav|aac|skin)$ {
      expires max;}
    - location = /robots.txt {
      allow all;}
    - location ~* ^(?:.+\.(?:htaccess|make|txt|engine|inc|info|install|module|profile|po|pot|sh|.*sql|test|theme|tpl(?:\.php)?|xtmpl)|code-style\.pl|/Entries.*|/Repository|/Root|/Tag|/Template)$ {
      deny all;
      access_log off;}
    - location ~ /\. {
      deny all;
      access_log off;
      log_not_found off;}
    - location ~ ^/sites/default/files/(.+)\.php$ {
      return 403;}
      ## Trying to access private files directly returns a 404.
    - location ^~ /sites/default/files/private/ {
      internal;}
    - location ~* ^/.well-known/ {allow all;}
    - location ~ ^/tmp/(.+)\.php$ {
      return 403;}
    - location / {
      try_files $uri @rewrite;}
    - location ~ '\.php$|^/update.php|/cron.php' {
      fastcgi_pass {{ site_name }};}
    - location @rewrite {rewrite ^/(.*)$ /index.php?q=$1;}
nginx_configs:
  upstream-{{ site_name }}:
    - upstream {{ site_name }} {server unix:/var/run/php-fpm-{{ site_name }}.sock;}
