---
- name: Remove unwanted sites
  file:
    path: "{{nginx_conf_dir}}/{{ item }}/{{ site_name }}.conf"
    state: absent
  with_items:
    - 'sites-enabled'
    - 'sites-available'
  notify:
   - reload nginx

- name: Remove unwanted conf
  file:
    path: "{{nginx_conf_dir}}/conf.d/upstream-{{ site_name }}.conf"
    state: absent
  notify:
   - reload nginx

