mysql_users:
  - name: "{{ mysql_user }}"
    host: "localhost"
    password: "{{ mysql_passwd }}"
    priv: "{{ mysql_db }}.*:ALL"

mysql_databases:
  - name: "{{ mysql_db }}"
    encoding: "{{ charset }}"
    collation: "{{ charset }}_general_ci"
